#!/bin/bash

 # check if there is the /mnt/wsl/docker.sock and is this is a socket file
 if [ -S /mnt/wsl/docker.sock ]; then
   echo "Docker is running!"
 else
   # create the symbolic link to the docker.sock for the other WSL2 instances
   rm -rf /mnt/wsl/docker.sock
   ln -sf /var/run/docker.sock /mnt/wsl/docker.sock
 fi
